### ISSUE TITLE
can not install pyvqnet

### ISSUE THREAD

**Issue by qinhui99** [OriginQ/VQNET2.0-tutorial#41]
hi,

We try to install pyvqnet throught the following command:
pip install pyvqnet --index-url https://pypi.originqc.com.cn

Then we got the error msg:
Looking in indexes: https://pypi.originqc.com.cn
ERROR: Could not find a version that satisfies the requirement pyvqnet (from versions: none)
ERROR: No matching distribution found for pyvqnet

And we try to visit the website( https://pypi.originqc.com.cn), still got some error. 
How can we install pyvqnet ?

**Comment by kevzos** [comment]
@qinhui99 Hello, please let me know your system version and Python version. Thank you.

**Comment by qinhui99** [comment]
Since the website( https://pypi.originqc.com.cn/) is OK, now I can install pyvqnet.  Thanks.
